services:
  - type: web
    name: server
    env: node
    plan: free
    buildCommand: |
      yarn install
      yarn nx build twenty-server
    startCommand: yarn workspace twenty-server start:prod
    domains:
      - twenty.com
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: FRONT_BASE_URL
        fromService:
          name: front
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: SERVER_URL
        fromService:
          name: server
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: APP_SECRET
        generateValue: true
      - key: PG_DATABASE_HOST
        fromService:
          name: twenty_postgres
          type: pserv
          property: host
      - key: PG_DATABASE_PORT
        fromService:
          name: twenty_postgres
          type: pserv
          property: port
  - type: web
    name: front
    env: node
    plan: free
    buildCommand: |
      yarn install
      yarn nx build twenty-front
    startCommand: yarn workspace twenty-front start:prod
    domains:
      - twenty.com
    envVars:
      - key: NODE_VERSION
        value: 18
  - type: worker
    name: worker
    env: node
    plan: free
    buildCommand: |
      yarn install
      yarn nx build twenty-server
    startCommand: yarn workspace twenty-server worker:prod
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: FRONT_BASE_URL
        fromService:
          name: front
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: SERVER_URL
        fromService:
          name: server
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: APP_SECRET
        generateValue: true
      - key: PG_DATABASE_HOST
        fromService:
          name: twenty_postgres
          type: pserv
          property: host
      - key: PG_DATABASE_PORT
        fromService:
          name: twenty_postgres
          type: pserv
          property: port
    disk:
      name: twenty-disk
      mountPath: /.local-storage
      sizeGB: 5
  - type: pserv
    name: twenty_postgres
    plan: starter
    ipAllowList: []
    postgres:
      version: 15
    disk:
      name: data
      sizeGB: 10
